import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import { dehydrate, HydrationBoundary } from '@tanstack/react-query';
import Header from '@/widgets/header/Header';
import Footer from '@/widgets/footer/Footer';
import './globals.scss';
import ReactQueryProvider from '@/shared/providers/ReactQueryProvider';
import { getQueryClient } from '@/shared/lib/getQueryClient';
import { prefetchCategories } from '@/entities/category/api/prefetch';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Pneumo',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const queryClient = getQueryClient();

  // Категории нужны меню, а меню есть на каждой странице — префетчим здесь,
  // чтобы хедер не мигал состоянием загрузки при первом заходе.
  await prefetchCategories(queryClient);

  return (
    <html lang="ru" className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}>
      <body className="min-h-full flex flex-col">
        <ReactQueryProvider>
          <HydrationBoundary state={dehydrate(queryClient)}>
            <Header />

            <main className="main">
              <div className="container">{children}</div>
            </main>

            <Footer />
          </HydrationBoundary>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
